variable "gcp_project" {
  type        = string
  default     = ""
  description = "The GCP project id in which the Cloud SQL instance will be deployed"
}

variable "gcp_region" {
  type        = string
  default     = ""
  description = "The GCP region in which the Cloud SQL instance will be deployed"
}

variable "instance_name" {
  type        = string
  description = "The name of the Cloud SQL instance"
}

variable "instance_version" {
  type        = string
  default     = "POSTGRES_14"
  description = "The Cloud SQL version string for the instance"
}

variable "instance_tier" {
  type        = string
  default     = "db-f1-micro"
  description = "The Cloud SQL instance tier to configure the underlying VM resources"
}

variable "instance_databases" {
  type        = list(string)
  default     = []
  description = "A list of database to create. WARNING: user permissions are not managed."
}

variable "instance_users" {
  type        = list(string)
  default     = []
  description = "A list of users to create. Password are generated by Terraform. WARNING: user permissions are not managed."
}
